name: 'terraform cd'

on:
  workflow_call:
    inputs:
      working-directory:
        type: string
        required: true
    secrets:
      github-token:
        required: true
      gcp-project-id:
        required: true
      workload-identity-provider:
        required: true
      service-account:
        required: true

env:
  TERRAFORM_VERSION: 1.1.6

jobs:
  terraform-cd:
    name: terraform-cd
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working-directory }}
    permissions:
      pull-requests: write
      id-token: write
      contents: read
    steps:
      - name: clone repository
        uses: actions/checkout@v2

      - name: authenticate to google cloud
        uses: google-github-actions/auth@v0
        with:
          create_credentials_file: true
          workload_identity_provider: ${{ secrets.workload-identity-provider }}
          service_account: ${{ secrets.service-account }}

      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: terraform fmt
        id: fmt
        run: terraform fmt

      - name: terraform init
        run: terraform init -reconfigure

      - name: terraform validate
        run: terraform validate

      - name: terraform apply
        id: apply
        run: |
          cp $GOOGLE_APPLICATION_CREDENTIALS $GITHUB_WORKSPACE/terraform/credential.json
          terraform apply -no-color -auto-approve -var 'gcp_project_id=${{ secrets.gcp-project-id }}'

      - name: comment
        uses: actions/github-script@v6
        env:
          APPLY: "terraform\n${{ steps.apply.outputs.stdout }}"
        with:
          github-token: ${{ secrets.github-token }}
          script: |
            const output = `## Work Directory: \`${{ inputs.working-directory }}\`
            #### Terraform Format and Style ðŸ–Œ\`${{ steps.fmt.outcome }}\`
            #### Terraform Apply ðŸ“–\`${{ steps.apply.outcome }}\`

            <details><summary>Show Apply Result</summary>

            \`\`\`${process.env.APPLY}\`\`\`

            </details>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })
